### ISSUE TITLE
GPL license confusion

### ISSUE THREAD

**Issue by tony** [jgm/peg-markdown#35]
I noticed this originally because I'm looking at a project that borrows code from this project https://github.com/hhatto/gorst/blob/master/parser.leg.

jQuery had this issue a while back:: https://blog.jquery.com/2012/09/10/jquery-licensing-changes/

I'm curious why to include mentioning of GPL if MIT is GPL compatible?

**Comment by jgm** [comment]
It's not uncommon to have dual-licensed projects.
See e.g.
http://programmers.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website

+++ Tony Narlock [Mar 16 16 09:30 ]:

**Comment by tony** [comment]
I read the StackExchange post. It cites jQuery as an example, which has since moved away from dual-licensing a few months after. The author of the answer is also mistaken.

> Why then it is also with GPL? This is because, if someone wants to make additional javascript library using jQuery, he/she can choose GPL license for himself/herself and distribute further in GPL to protect the freedom (which won't be possible with MIT).

It's possible. MIT code is forward compatible GPL. You could fork a pure MIT project and license it GPL.   That's my primary point, dual licensing in this context is redundant, which is why jQuery dropped it.

If you have already made your mind made up, you can close the issue. If you need more proof to demonstrate why it's redundant or confusing, I can provide it.

**Comment by jgm** [comment]
It's pointless to worry about this now.  Changing the
license would require getting permission of all
contributors.  And this is a project I don't really
maintain any more.

I don't see what the down side of a dual license is,
anyway.  The license explicitly permits you to treat this
as if it's MIT licensed.
