### ISSUE TITLE
PEG parser for other than markdown

### ISSUE THREAD

**Issue by Rizary** [jgm/peg-markdown#42]
Hi, I am sorry that I have to open an issue for my question.

I really like your work on markdown parsing. I am currently trying to built some parser library with one of my language and think to use Parsing expression grammar(PEG) as my parser. I recently find this repo and it seems it is not updated in the long time.

While I see your work on commonmark-hs and it seems you are not using PEG as a parser. I am quite new in this field so apologize if I'm wrong. May I ask why you are not using PEG for your commonmark-hs?

Maybe my project is not relevant to markdown or commonmark, but I just want to have second opinion on using PEG parser.

**Comment by jgm** [comment]
Search on talk.commonmark.org for discussions of formal grammars.
